### ISSUE TITLE
Invalid HTML as checked by W3C Validator

### ISSUE THREAD

**Issue by n1trux** [AfeefaDe/bitbaum#7]
The [W3C Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fbits-und-baeume.org%2Fde) gives several errors:

Error: Bad value expires for attribute http-equiv on element meta.

```
-origin">↩<meta http-equiv="expires" content="Mon, 26 Jul 1997 05:00:00 GMT"/>↩<meta
```

Error: Bad value Pragma for attribute http-equiv on element meta.

```
00 GMT"/>↩<meta http-equiv="Pragma" content="no-cache">↩↩<met
```

Both of the "Bad value" errors can be resolved by [only using HTTP headers for caching instructions](https://stackoverflow.com/questions/12693630/bad-values-in-meta-tags/31404413#31404413).

---

Error: End tag section seen, but there were open elements.

```
>↩        </section>↩     
```

Error: Unclosed element article.

```
          <article>↩     
```

Both of these can be solved by properly nesting/opening/closing your tags.

---

Please make the HTML valid so it can be rendered properly by all browsers.

**Comment by friedrichweise** [comment]
Fixed by 19956a4a18685181cc173161104744a6667b4de7 and d5bae51e644d43632e224c15f814bbc0bc004a7c

Sorry it took me so long to get to your issue. I started watching the repo and should be able to response quicker in the future.
